sudo: false
language: objective-c
rvm:
  - 1.9.3
  - 2.1.3

cache: bundler

os:
  - osx

before_install:
  - brew install youtube-dl

before_script:
  - which youtube-dl
  - youtube-dl --version

script: bundle exec rake spec
