sudo: false
language: objective-c
rvm:
  - 2.2.3
  - 2.3.0

cache: bundler

os:
  - osx

before_install:
  - brew install youtube-dl

before_script:
  - which youtube-dl
  - youtube-dl --version

script: bundle exec rake spec
